# Generated by Django 5.0.6 on 2024-06-02 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodo', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasktodo_ta_publish_b65f71_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='publish',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created'], name='tasktodo_ta_created_a73799_idx'),
        ),
    ]
