# Generated by Django 5.0.6 on 2024-06-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodo', '0003_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Acepted', 'aceptd'), ('In progress', 'in progress'), ('Completed', 'completed')], default='Acepted', max_length=50),
        ),
    ]
